version: '3'
services:
  go:
    build: docker/go
    volumes:
      - ".:/go/src/app"
    command: bee run
  nginx:
    build: docker/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - go
